/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studiobooking;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Date;
//import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author deviparamita
 * tgl = 28 Juni 2025
 */
public class AdminForm extends javax.swing.JFrame {
    private void tampilkanDataBooking() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Tanggal");
    model.addColumn("Jam Mulai");
    model.addColumn("Jam Selesai");
    model.addColumn("Durasi");
    model.addColumn("Studio");
    model.addColumn("Status");

    try {
        Connection conn = DBConnection.getConnection();
        String sql = "SELECT * FROM booking";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_booking"),
                rs.getString("nama"),
                rs.getDate("tanggal"),
                rs.getString("jam_mulai"),
                rs.getString("jam_selesai"),
                rs.getString("durasi"),
                rs.getString("studio"),
                rs.getString("status")
            });
        }

        bookingTable.setModel(model);

        rs.close();
        pst.close();
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal tampilkan data: " + e.getMessage());
    }
}


    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
    initComponents();
    
    statusComboBox.removeAllItems(); // hapus semua item lama (seperti "Item 1")
    statusComboBox.addItem("pending");
    statusComboBox.addItem("approved");
    statusComboBox.addItem("cancelled");


    // Sembunyikan ID Booking
    idBookingField.setVisible(false);
    jLabelId.setVisible(false);

    // Load data booking
    tampilkanDataBooking();

    // Set kondisi awal tombol
   
    editButton.setEnabled(false); // <--- kalau kamu pakai tombol edit
    hapusButton.setEnabled(false);
    batalButton.setEnabled(true); // <--- biar user bisa bersihin input
    simpanButton.setEnabled(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        idBookingField = new javax.swing.JTextField();
        jLabelNama = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabelTanggal = new javax.swing.JLabel();
        jLabelJamMulai = new javax.swing.JLabel();
        jamMulaiField = new javax.swing.JTextField();
        jLabelDurasi = new javax.swing.JLabel();
        durasiField = new javax.swing.JTextField();
        jLabelStudio = new javax.swing.JLabel();
        studioField = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        simpanButton = new javax.swing.JButton();
        tanggalField = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        jLabelJamSelesai = new javax.swing.JLabel();
        jamSelesaiField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tutupButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("BOOKING FORM");

        jLabelId.setText("ID Booking");

        jLabelNama.setText("Nama");

        jLabelTanggal.setText("Tanggal");

        jLabelJamMulai.setText("Jam Mulai");

        jamMulaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamMulaiFieldActionPerformed(evt);
            }
        });

        jLabelDurasi.setText("Durasi");

        jLabelStudio.setText("Studio");

        jLabelStatus.setText("Status");

        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingTable);

        jLabelJamSelesai.setText("Jam Selesai");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDurasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(durasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJamMulai)
                                    .addComponent(jLabelTanggal)
                                    .addComponent(jLabelJamSelesai)
                                    .addComponent(jLabelNama)
                                    .addComponent(jLabelId))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tanggalField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(jamMulaiField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(idBookingField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(jamSelesaiField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelStatus)
                                    .addComponent(jLabelStudio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studioField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(simpanButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabelTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addGap(22, 22, 22)
                        .addComponent(hapusButton)
                        .addGap(18, 18, 18)
                        .addComponent(batalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tutupButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelTitle)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(idBookingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jamMulaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelJamMulai))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelJamSelesai)
                                    .addComponent(jamSelesaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(durasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDurasi))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(studioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStudio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStatus))
                                .addGap(31, 31, 31)
                                .addComponent(simpanButton))
                            .addComponent(jLabelTanggal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editButton)
                        .addComponent(hapusButton)
                        .addComponent(batalButton))
                    .addComponent(tutupButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jamMulaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamMulaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamMulaiFieldActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed

    try {
    Connection conn = DBConnection.getConnection();
    String sql = "INSERT INTO booking (nama, tanggal, jam_mulai, jam_selesai, durasi, studio, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, namaField.getText());

    java.util.Date selectedDate = tanggalField.getDate();
    java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
    pst.setDate(2, sqlDate);

    pst.setString(3, jamMulaiField.getText());
    pst.setString(4, jamSelesaiField.getText());
    pst.setString(5, durasiField.getText());
    pst.setString(6, studioField.getText());
    pst.setString(7, "pending");

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");

    pst.close();
    conn.close();

    // Ini WAJIB agar JTable langsung refresh datanya
    tampilkanDataBooking();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
}


    }//GEN-LAST:event_simpanButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
                                         
    try {
        Connection conn = DBConnection.getConnection();
        String sql = "UPDATE booking SET nama=?, tanggal=?, jam_mulai=?, jam_selesai=?, durasi=?, studio=?, status=? WHERE id_booking=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, namaField.getText());
        java.util.Date selectedDate = tanggalField.getDate();
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        pst.setDate(2, sqlDate);
        pst.setString(3, jamMulaiField.getText());
        pst.setString(4, jamSelesaiField.getText());
        pst.setString(5, durasiField.getText());
        pst.setString(6, studioField.getText());
        pst.setString(7, (String) statusComboBox.getSelectedItem());
        pst.setInt(8, Integer.parseInt(idBookingField.getText())); // ID disembunyikan tapi tetap dibaca

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
        tampilkanDataBooking(); // refresh table
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal edit data: " + e.getMessage());
    }


    }//GEN-LAST:event_editButtonActionPerformed

    private void bookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingTableMouseClicked
                                          
    int row = bookingTable.getSelectedRow();
    if (row != -1) {
        idBookingField.setText(bookingTable.getValueAt(row, 0).toString());
        namaField.setText(bookingTable.getValueAt(row, 1).toString());
        tanggalField.setDate(java.sql.Date.valueOf(bookingTable.getValueAt(row, 2).toString()));
        jamMulaiField.setText(bookingTable.getValueAt(row, 3).toString());
        jamSelesaiField.setText(bookingTable.getValueAt(row, 4).toString());
        durasiField.setText(bookingTable.getValueAt(row, 5).toString());
        studioField.setText(bookingTable.getValueAt(row, 6).toString());
        statusComboBox.setSelectedItem(bookingTable.getValueAt(row, 7).toString());

        // Aktifkan tombol edit dan hapus, matikan simpan
        simpanButton.setEnabled(false);
        
        editButton.setEnabled(true);
        hapusButton.setEnabled(true);
    }


    }//GEN-LAST:event_bookingTableMouseClicked

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
    kosongkanForm();                      // reset semua inputan
          // nonaktifkan tombol update
    hapusButton.setEnabled(false);        // nonaktifkan tombol hapus
    simpanButton.setEnabled(true);        // aktifkan tombol simpani nggak ngedit

    }//GEN-LAST:event_batalButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
   int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    try {
        Connection conn = DBConnection.getConnection();
        String sql = "DELETE FROM booking WHERE id_booking = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(idBookingField.getText()));
        pst.executeUpdate();
        pst.close();
        conn.close();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");

        tampilkanDataBooking(); // Refresh isi tabel
        kosongkanForm();        // Kosongkan semua input

        // Reset tombol
        
        
        simpanButton.setEnabled(true);
        hapusButton.setEnabled(!idBookingField.getText().isEmpty());

        


    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
    }
}



    }//GEN-LAST:event_hapusButtonActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
     dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JTable bookingTable;
    private javax.swing.JTextField durasiField;
    private javax.swing.JButton editButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField idBookingField;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelJamMulai;
    private javax.swing.JLabel jLabelJamSelesai;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStudio;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jamMulaiField;
    private javax.swing.JTextField jamSelesaiField;
    private javax.swing.JTextField namaField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField studioField;
    private com.toedter.calendar.JDateChooser tanggalField;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
    // End of variables declaration                   

    private void kosongkanForm() {
    idBookingField.setText("");
    namaField.setText("");
    tanggalField.setDate(null);
    jamMulaiField.setText("");
    jamSelesaiField.setText("");
    durasiField.setText("");
    studioField.setText("");
    statusComboBox.setSelectedIndex(0);
    
    simpanButton.setEnabled(true);
    hapusButton.setEnabled(false);

}


} // <- penutup class AdminForm





